### ISSUE TITLE
NetBeans MoppyDesk Project Run Problem

### ISSUE THREAD

**Issue by Toastdude** [samphonic/MoppyClassic#13]
Hello,

```
I've been trying to get the MoppyDesk project to work in NetBeans, and it seems like it is working, but I don't get a window. If it helps, this is what the console says: 
```

run:
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.MoppyMainWindow.updateComSelectionMenu(MoppyMainWindow.java:55)
    at moppydesk.MoppyMainWindow.<init>(MoppyMainWindow.java:43)
    at moppydesk.MoppyUI.startup(MoppyUI.java:19)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

I'm very new at this, so please forgive me for not knowing much about this stuff.
Thanks!
  -Toastdude

**Comment by minihui** [comment]
Hello Toastdude, you'll need to have the rxtxComm installed. The installation procedure is located in Java/SerialDrivers/rxtx-2.1-7-bins-r2/INSTALL. Have fun!

**Comment by Toastdude** [comment]
Thank you for your reply, minihui!
I had thought I installed it correctly, but I didn't.

Thank you!

**Comment by minihui** [comment]
So you successfully made it working? Glad to hear that mate!

**Comment by Toastdude** [comment]
Yep! I was a little confused on which jre folder at first to install the stuff into. But now the next problem: Getting more floppy drives!

**Comment by samphonic** [comment]
Excellent, thanks Toastdude.
