### ISSUE TITLE
Everytime i try and run moppy in net beans i get this message.....

### ISSUE THREAD

**Issue by bbdragon84** [samphonic/MoppyClassic#16]
java.lang.UnsatisfiedLinkError: C:\Users\BenB\Desktop\SammyIAm-Moppy-15e2b0c\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Users\BenB\Desktop\SammyIAm-Moppy-15e2b0c\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1854)
    at java.lang.Runtime.loadLibrary0(Runtime.java:845)
    at java.lang.System.loadLibrary(System.java:1084)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.MoppyMainWindow.updateComSelectionMenu(MoppyMainWindow.java:55)
    at moppydesk.MoppyMainWindow.<init>(MoppyMainWindow.java:43)
    at moppydesk.MoppyUI.startup(MoppyUI.java:19)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:701)
    at java.awt.EventQueue.access$000(EventQueue.java:102)
    at java.awt.EventQueue$3.run(EventQueue.java:662)
    at java.awt.EventQueue$3.run(EventQueue.java:660)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:671)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

**Comment by minihui** [comment]
That's another rxtxComm issue. Use the 32bit .dll instead.

**Comment by samphonic** [comment]
Thanks minihui.  Yeah, by default the code is trying to load a 64-bit dll, you'll just have to switch it to the 32-bit version.
