### ISSUE TITLE
Running on an Arduino Duemilenove?

### ISSUE THREAD

**Issue by DefectX11** [samphonic/MoppyClassic#25]
I seem to be having an issue running the program on a Duemilenove. I believe I have set it up to the extent of my knowledge, and my wiring is good (enough). However, when I connect to the single drive (pins 2+3), select the midi output to channel 1, and play a sample song, all the drive does is tick.

I've tested manually stepping the drive and shifting direction- that all works, so the drive is not dead. But it just won't play the file, which confuses me- the only difference is the board- Would it cause an issue like this? Possibly timing?

Any input would be very helpful, thanks.

**Comment by AmEv7Fam** [comment]
Try reversing your Step and Direction leads.

**Comment by DefectX11** [comment]
Yep, my dyslexia kicked in and I read the directions incorrectly. 

Second question- gnu.io.NoSuchPortException error when connecting with 2 drives. Works 100% with 1 drive. 

?

Thanks!

**Comment by samphonic** [comment]
Exceptions on the Java-side of things won't be related to the connections on the Arduino-side of things.

Generally that exception means that the select COM port doesn't exist.  Are you trying to run two instances of Moppy, or two Arduinos?

**Comment by DefectX11** [comment]
No, and more surprisingly (as before) I replaced my Duemilenove with an Uno just for the extra measure.

It works 100% with the master copy of Moppy, but I'd like to be able to do more drives and have direct MIDI in, which is what the advanced version supports.

**Comment by samphonic** [comment]
Oh oh, I didn't know you were running the advanced branch (I guess GitHub doesn't differentiate in the issues area, so I've added a tag now... still learning this Github thing).

For two drives, you should have the check box selected for channel 1 and 2, the Moppy radio box selected, and the same COM port selected for both of them.  e.g. If you Arduino is on COM7, it would look like this:
![2Drives](https://f.cloud.github.com/assets/467704/48982/0c318e8c-5933-11e2-88d8-acaa3f1a444f.JPG)

(Sorry if you've done this already, I'm just trying to get a handle on what your settings are now to figure out what might be causing the issue.

**Comment by DefectX11** [comment]
Done and done. I will try again later tonight, but I have done this exactly across 4 computers, 2 with 7 64 and 2 with 8 64

**Comment by samphonic** [comment]
I should have asked for this earlier, but could you provide a full stack-trace of the NoSuchPortException so I can see where it's coming from?  Maybe that'll help nail this down (it's hard to debug since I can't reproduce the error on this end).

**Comment by DefectX11** [comment]
Sure, just give me some time to do that. I'm quite bogged down with work
ATM.

On Tue, Jan 8, 2013 at 11:21 AM, SammyIAm notifications@github.com wrote:

> I should have asked for this earlier, but could you provide a full
> stack-trace of the NoSuchPortException so I can see where it's coming from?
> Maybe that'll help nail this down (it's hard to debug since I can't
> reproduce the error on this end).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/SammyIAm/Moppy/issues/25#issuecomment-12012647.

## 

//Gordon

**Comment by samphonic** [comment]
No rush at all; whenever you get to it.  =)

**Comment by DefectX11** [comment]
Hopefully this is what you're looking for.

Jan 10, 2013 6:11:39 PM moppydesk.ui.MoppyControlWindow connect
SEVERE: null
gnu.io.NoSuchPortException
    at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:269)
    at moppydesk.outputs.MoppyCOMBridge.<init>(MoppyCOMBridge.java:29)
    at moppydesk.ui.MoppyControlWindow.initializeReceivers(MoppyControlWindow.java:254)
    at moppydesk.ui.MoppyControlWindow.connect(MoppyControlWindow.java:201)
    at moppydesk.ui.MoppyControlWindow.connectButtonActionPerformed(MoppyControlWindow.java:284)
    at moppydesk.ui.MoppyControlWindow.access$100(MoppyControlWindow.java:29)
    at moppydesk.ui.MoppyControlWindow$2.actionPerformed(MoppyControlWindow.java:128)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6505)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6270)
    at java.awt.Container.processEvent(Container.java:2229)
    at java.awt.Component.dispatchEventImpl(Component.java:4861)
    at java.awt.Container.dispatchEventImpl(Container.java:2287)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
    at java.awt.Container.dispatchEventImpl(Container.java:2273)
    at java.awt.Window.dispatchEventImpl(Window.java:2719)
    at java.awt.Component.dispatchEvent(Component.java:4687)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:682)
    at java.awt.EventQueue$3.run(EventQueue.java:680)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
    at java.awt.EventQueue$4.run(EventQueue.java:696)
    at java.awt.EventQueue$4.run(EventQueue.java:694)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by samphonic** [comment]
Huh, weird.  The error seems to be happening when the program tries to initialize the COM port, but I can't think of anything off-hand that would cause that error other than the port not existing.  When you've got time to debug a little more, try putting a breakpoint (click on the left side of the code editing area to make a little red box appear) on line 29 of MoppyCOMBridge.java.  And then instead of pressing "Run", press "Debug".

When it gets to the breakpoint, hover your mouse over the "portName" variable and it should tell you what that variable equals.  It SHOULD say something like "COM7" or wherever your Arduino is connected.  Take note of the value, and then press F5.  Depending on if you've got multiple channels selected, it should either continue to run normally, or it will come back around again and stop at the breakpoint for the second channel.  If it stops again, take note again of the value of "portName".

Try this for both the working-case (with just one channel), and the case where you get the error and let me know what the values are.  I'm beginning to suspect I might have screwed up a menu somewhere.

**Comment by samphonic** [comment]
Closing due to inactivity.
