### ISSUE TITLE
Serial Driver incompatible with Arduino SDK

### ISSUE THREAD

**Issue by ZEBaker98** [samphonic/MoppyClassic#39]
I managed to install the RXTX Serial Driver and get Moppy to work however later when I was uploading a sketch to my arduino the upload crashed the SDK. Upon further research I found that the RXTX driver was the cause. Is there any way to fix this? I am on a MacBook.

**Comment by samphonic** [comment]
I don't have a lot of experience using OS X with Arduinos and Moppy, but I've got a couple things to try:

Where did you "install" the RXTX driver?  Is the OS X Arduino IDE Java-based?  If you installed the driver to a central Java location, then it may be loading it when you run the IDE.  Rather than installing it there, try just putting it into a folder somewhere safe, and using the java.library.path argument when launching Moppy.

Also make sure you don't have Moppy open at the same time you're trying to upload software from the IDE.  I believe only one program can be using the serial port a time.

**Comment by ZEBaker98** [comment]
I installed the RXTX driver to the Global Java Path. If i remove it then Arduino uploads fine.The OS X IDE is java based and after some searching actually has the RXTX Driver in the app file. Maybe a version incompatibility?

**Comment by samphonic** [comment]
Yeah, sounds like it.  Definitely try launching Moppy using the java.library.path argument (Google for exact syntax) and just keeping the RXTX for Moppy in a separate folder outside the normal Java path.

Alternatively, you could try copying the RXTX Driver from the Arduino IDE app into the Global Java Path and see if Moppy will be okay with it.  Moppy isn't doing anything advanced with the serial port, so as long as they're mostly similar, it might be happy with it.

**Comment by ZEBaker98** [comment]
When running Moppy with the RXTX supplied by the Arduino IDE it returned:
ava.lang.UnsatisfiedLinkError: /System/Library/Java/Extensions/librxtxSerial.jnilib:  no suitable image found.  Did find:  /System/Library/Java/Extensions/librxtxSerial.jnilib: no matching architecture in universal wrapper thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: /System/Library/Java/Extensions/librxtxSerial.jnilib:  no suitable image found.  Did find:  /System/Library/Java/Extensions/librxtxSerial.jnilib: no matching architecture in universal wrapper
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1827)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1716)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1045)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
    at moppydesk.outputs.MoppyCOMBridge.getAvailableCOMPorts(MoppyCOMBridge.java:113)
    at moppydesk.ui.ChannelOutControl.initComponents(ChannelOutControl.java:123)
    at moppydesk.ui.ChannelOutControl.<init>(ChannelOutControl.java:31)
    at moppydesk.ui.MoppyControlWindow.setupOutputControls(MoppyControlWindow.java:77)
    at moppydesk.ui.MoppyControlWindow.<init>(MoppyControlWindow.java:58)
    at moppydesk.MoppyUI.startup(MoppyUI.java:50)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by samphonic** [comment]
Alright, one more shot at getting these to work simultaneously.  If you download the source code for the Arduino IDE, in the app/lib folder there is an RXTXcomm.jar file.  Replace the RXTXcomm.jar that came with Moppy with the one from the Arduino source (make a backup first in case it doesn't work).

You _might_ get some errors in NetBeans, but they're probably fixable.  If you _don't_ get any errors, then give it one more go.

**Comment by ZEBaker98** [comment]
No that didn't fix it. It's fine though Ill just uninstall the driver and then install it just when i'm doing moppy stuff.

**Comment by samphonic** [comment]
Alright, worth a shot at least.
