### ISSUE TITLE
Getting MoppyDesk to Work in NetBeans

### ISSUE THREAD

**Issue by hunterirving** [samphonic/MoppyClassic#42]
Hey! I'm working on a floppy drive setup with Moppy, and I'm so close I can taste it.

NetBeans throws this exception:

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
java.lang.UnsatisfiedLinkError: C:\Windows\System32\rxtxSerial.dll: %1 is not a valid Win32 application thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Windows\System32\rxtxSerial.dll: %1 is not a valid Win32 application
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.MoppyMainWindow.updateComSelectionMenu(MoppyMainWindow.java:55)
    at moppydesk.MoppyMainWindow.<init>(MoppyMainWindow.java:43)
    at moppydesk.MoppyUI.startup(MoppyUI.java:19)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Any help would be greatly appreciated!

**Comment by hunterirving** [comment]
Somehow it works now?
Thanks anyways, all!

**Comment by samphonic** [comment]
Hooray, glad it works now!

**Comment by Android055** [comment]
I've experienced the same problem. How is it fixed?
