### ISSUE TITLE
Mac_OS_X  VM Options

### ISSUE THREAD

**Issue by Phoenix674** [samphonic/MoppyClassic#43]
Im running Mac OS X Mavericks and I can't seem to find the right VM options and continuously get either a failed build or 

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.outputs.MoppyCOMBridge.getAvailableCOMPorts(MoppyCOMBridge.java:113)
    at moppydesk.ui.ChannelOutControl.initComponents(ChannelOutControl.java:123)
    at moppydesk.ui.ChannelOutControl.<init>(ChannelOutControl.java:31)
    at moppydesk.ui.MoppyControlWindow.setupOutputControls(MoppyControlWindow.java:77)
    at moppydesk.ui.MoppyControlWindow.<init>(MoppyControlWindow.java:58)
    at moppydesk.MoppyUI.startup(MoppyUI.java:50)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)  

Im not sure if the "librxtxSerial.jnilib" file is working, or if Net beans just can't use it because of different versions.  I'm extremely confused and am pretty sure that it has something to do with the VM options, Help please.

Thanks in advance.

**Comment by gorhgorh** [comment]
hi there, i just went through the installation process on Maverick this weekend so maybe i'll be able to help you out a bit .

i had hard time compiling rxtx so i used the one given [here](http://blog.iharder.net/2009/08/18/rxtx-java-6-and-librxtxserial-jnilib-on-intel-mac-os-x/).

i copied both RXTXcomm.jar and librxtxSerial.jnilib to /Library/Java/Extensions. 

in my netbean project i changed the vm option line (found in the "run" categorie, not in the "run" tab of the "libraries" one) to : 

```
-Djava.library.path="/Library/Java/Extensions"
```

you should now be able to compile .

IF you run into permission issue after you should either fix the perm issues / copy the files elsewhere (in your project ?) and point there instead. 

hope it helps, and if you run into more troubles i would be happy to help with :) 

to test if your setup is working, you could also use [this program](https://code.google.com/p/moppy-desk-launcher-mac/) that contain a pre compiled version of Moppy. 

enjoy floppy music :)

**Comment by Phoenix674** [comment]
Hi, again, thanks for the help earlier gorhgorh, that seemed to do the trick.  Now i only have one more problem, when i try to upload the program to the Arduino, i can't get the right ports or the ports are already being used.  It comes up with this error...

Binary sketch size: 3,808 bytes (of a 32,256 byte maximum)
processing.app.SerialException: Serial port '/dev/cu.usbmodem1411' already in use. Try quiting any programs that may be using it.
    at processing.app.Serial.<init>(Serial.java:171)
    at processing.app.Serial.<init>(Serial.java:77)
    at processing.app.debug.Uploader.flushSerialBuffer(Uploader.java:77)
    at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:174)
    at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
    at processing.app.Sketch.upload(Sketch.java:1671)
    at processing.app.Sketch.exportApplet(Sketch.java:1627)
    at processing.app.Sketch.exportApplet(Sketch.java:1599)
    at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
    at java.lang.Thread.run(Thread.java:695)
processing.app.debug.RunnerException: Serial port '/dev/cu.usbmodem1411' already in use. Try quiting any programs that may be using it.
    at processing.app.debug.Uploader.flushSerialBuffer(Uploader.java:101)
    at processing.app.debug.AvrdudeUploader.uploadViaBootloader(AvrdudeUploader.java:174)
    at processing.app.debug.AvrdudeUploader.uploadUsingPreferences(AvrdudeUploader.java:67)
    at processing.app.Sketch.upload(Sketch.java:1671)
    at processing.app.Sketch.exportApplet(Sketch.java:1627)
    at processing.app.Sketch.exportApplet(Sketch.java:1599)
    at processing.app.Editor$DefaultExportHandler.run(Editor.java:2380)
    at java.lang.Thread.run(Thread.java:695)

Is there any special drivers that i have to use for Mac, versus Windows 7?  I have preformed projects on the windows machine, but never on the mac, thus why i seem to be having problems.  I do have the Arduino IDE for Mac, and i have tried the trouble shooting section on Arduino.cc.

Thanks in advance.

**Comment by samphonic** [comment]
This doesn't seem to be an issue with Moppy, but just with your Arduino IDE / hardware set up.

You'll be better off looking for help in an Arduino-specific forum or on Google than here.  Sorry I can't be more helpful.
