### ISSUE TITLE
Issues with Moppy in Ubuntu 14.04

### ISSUE THREAD

**Issue by RedFox1177** [samphonic/MoppyClassic#73]
When I open moppy in netbeans, it opens a tiny box for a half second, and in it is the letter O. Sorry this is all I have, I also have a windows partition, would it be better in windows?

**Comment by MultiDaxio** [comment]
Is NetBeans even optimized for Ubuntu? If not, switch to Windows, or look
for wider optimized version. OS shouldn`t cause any troubles though...

**Comment by samphonic** [comment]
@RedFox1177 , is the tiny box showing up when you open up the NetBeans project, or when you press the "Run" button after having it open?  Which version of NetBeans are you using?

Ubuntu shouldn't cause any issues with NetBeans; I've used them together pretty often.

**Comment by RedFox1177** [comment]
@SammyIAm , I just installed netbeans by the command sudo apt-get install netbeans. It says I have ver. 1.6 of the jdk. Netbeans is 7.0.1. The tiny box is when I load moppydesk. The box shows, then closes. It looks like it can be expanded, but its too quick. Again, I'm dual booting Windows and Ubuntu, so I can do it in windows.

**Comment by RedFox1177** [comment]
@MultiDaxio,  I'm assuming that since oracle puts out Netbeans, java and Oracle Linux, it should be optimized

**Comment by MultiDaxio** [comment]
Ok. You`ve got the point.

**Comment by RedFox1177** [comment]
OK, an update. Installing netbeans 8.0 with jdk 1.8.0u5. Will this work?

**Comment by RedFox1177** [comment]
@SammyIAm When i run it now, it throws this error:

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1119)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.outputs.MoppyCOMBridge.getAvailableCOMPorts(MoppyCOMBridge.java:113)
    at moppydesk.ui.ChannelOutControl.initComponents(ChannelOutControl.java:123)
    at moppydesk.ui.ChannelOutControl.<init>(ChannelOutControl.java:31)
    at moppydesk.ui.MoppyControlWindow.setupOutputControls(MoppyControlWindow.java:77)
    at moppydesk.ui.MoppyControlWindow.<init>(MoppyControlWindow.java:58)
    at moppydesk.MoppyUI.startup(MoppyUI.java:50)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by samphonic** [comment]
Alright, glad you got it working (or closer at least)!

The issue you've got now is that you need to make sure you have the rxtxcomm native libraries on your Java path.  You can modify the NetBeans project to add the -Djava.library.path argument to specify which folder contains the native libraries.

On Ubuntu, I believe there is a way to install the Java rxtxcomm libraries using apt-get, but I don't remember exactly off hand how it works.  Google should help you there.  Additionally, you'll probably need to replace the reference in the project to the rxtxcomm.jar file with a reference to the .jar file that gets installed with the native libraries you install so that the libraries and jar file match.

**Comment by RedFox1177** [comment]
Ok, will try. I have the amd64 edition, and in the serial drivers, and it appears that there's not an amd64 edition.

**Comment by RedFox1177** [comment]
ok, im back to this never ending nightmare that is my computer. i have windows 7 ultimate x32 running, and its still throwing an error. the error reads (probably the same as last time,
java.lang.UnsatisfiedLinkError: C:\Users\Owen\Desktop\Moppy-moppy-advanced\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform thrown while loading gnu.io.RXTXCommDriver
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: C:\Users\Owen\Desktop\Moppy-moppy-advanced\Java\SerialDrivers\rxtx-2.1-7-bins-r2\Windows\ch-rxtx-2.2-20081207-win-x64\rxtxSerial.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1880)
    at java.lang.Runtime.loadLibrary0(Runtime.java:849)
    at java.lang.System.loadLibrary(System.java:1088)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
    at moppydesk.outputs.MoppyCOMBridge.getAvailableCOMPorts(MoppyCOMBridge.java:113)
    at moppydesk.ui.ChannelOutControl.initComponents(ChannelOutControl.java:123)
    at moppydesk.ui.ChannelOutControl.<init>(ChannelOutControl.java:31)
    at moppydesk.ui.MoppyControlWindow.setupOutputControls(MoppyControlWindow.java:77)
    at moppydesk.ui.MoppyControlWindow.<init>(MoppyControlWindow.java:58)
    at moppydesk.MoppyUI.startup(MoppyUI.java:50)
    at org.jdesktop.application.Application$1.run(Application.java:171)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

**Comment by jazzbassNick** [comment]
That latest one is a mismatch between 32 & 64.  Sounds like you need the
x32 rxtx when you run it in Windows

**Comment by RedFox1177** [comment]
Ok, I'll get it. I don't know where, but I'll find it.

**Comment by samphonic** [comment]
RXTX is no longer being used.  NRJavaSerial includes native libraries and should work without any additional configuration.  Give it a try!
